package edu.hziee.models;

public class Activitys {
    private Integer id;
    private String name;
    private Integer userId;
    private Integer startTime;
    private Integer endTime;
    private String place;

    private Integer peopleCount;
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.id
     *
     * @param id the value for activitys.id
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitys.name
     *
     * @return the value of activitys.name
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.name
     *
     * @param name the value for activitys.name
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitys.user_id
     *
     * @return the value of activitys.user_id
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.user_id
     *
     * @param userId the value for activitys.user_id
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitys.start_time
     *
     * @return the value of activitys.start_time
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.start_time
     *
     * @param startTime the value for activitys.start_time
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitys.end_time
     *
     * @return the value of activitys.end_time
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.end_time
     *
     * @param endTime the value for activitys.end_time
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitys.place
     *
     * @return the value of activitys.place
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.place
     *
     * @param place the value for activitys.place
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitys.people_count
     *
     * @return the value of activitys.people_count
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public Integer getPeopleCount() {
        return peopleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitys.people_count
     *
     * @param peopleCount the value for activitys.people_count
     *
     * @mbg.generated Sun Dec 11 22:05:22 CST 2016
     */
    public void setPeopleCount(Integer peopleCount) {
        this.peopleCount = peopleCount;
    }
}