package edu.hziee.models;

public class Attendactivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendactivity.activity_id
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendactivity.user_id
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendactivity.activity_id
     *
     * @return the value of attendactivity.activity_id
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendactivity.activity_id
     *
     * @param activityId the value for attendactivity.activity_id
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendactivity.user_id
     *
     * @return the value of attendactivity.user_id
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendactivity.user_id
     *
     * @param userId the value for attendactivity.user_id
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}