package edu.hziee.models;

public class CheckActivityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_activity.activity_id
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_activity.user_id
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_activity.activity_id
     *
     * @return the value of check_activity.activity_id
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_activity.activity_id
     *
     * @param activityId the value for check_activity.activity_id
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_activity.user_id
     *
     * @return the value of check_activity.user_id
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_activity.user_id
     *
     * @param userId the value for check_activity.user_id
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}