package edu.hziee.models;

public class CollectactivityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectactivity.activity_id
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectactivity.user_id
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectactivity.activity_id
     *
     * @return the value of collectactivity.activity_id
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectactivity.activity_id
     *
     * @param activityId the value for collectactivity.activity_id
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectactivity.user_id
     *
     * @return the value of collectactivity.user_id
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectactivity.user_id
     *
     * @param userId the value for collectactivity.user_id
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}