package edu.hziee.models;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.showname
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    private String showname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.power
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    private Integer power;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.showname
     *
     * @return the value of user.showname
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public String getShowname() {
        return showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.showname
     *
     * @param showname the value for user.showname
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public void setShowname(String showname) {
        this.showname = showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.power
     *
     * @return the value of user.power
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.power
     *
     * @param power the value for user.power
     *
     * @mbg.generated Sat Dec 10 14:14:41 CST 2016
     */
    public void setPower(Integer power) {
        this.power = power;
    }
}