package edu.hziee.mappers;

import edu.hziee.models.Attendactivity;
import edu.hziee.models.AttendactivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendactivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    long countByExample(AttendactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    int deleteByExample(AttendactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    int insert(Attendactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    int insertSelective(Attendactivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    List<Attendactivity> selectByExample(AttendactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") Attendactivity record, @Param("example") AttendactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendactivity
     *
     * @mbg.generated Mon Dec 12 12:17:13 CST 2016
     */
    int updateByExample(@Param("record") Attendactivity record, @Param("example") AttendactivityExample example);
}