package edu.hziee.mappers;

import edu.hziee.models.CheckActivityExample;
import edu.hziee.models.CheckActivityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    long countByExample(CheckActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    int deleteByExample(CheckActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    int deleteByPrimaryKey(CheckActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    int insert(CheckActivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    int insertSelective(CheckActivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    List<CheckActivityKey> selectByExample(CheckActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") CheckActivityKey record, @Param("example") CheckActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_activity
     *
     * @mbg.generated Tue Dec 13 18:52:33 CST 2016
     */
    int updateByExample(@Param("record") CheckActivityKey record, @Param("example") CheckActivityExample example);
}