package edu.hziee.mappers;

import edu.hziee.models.CollectactivityExample;
import edu.hziee.models.CollectactivityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectactivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    long countByExample(CollectactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    int deleteByExample(CollectactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    int deleteByPrimaryKey(CollectactivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    int insert(CollectactivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    int insertSelective(CollectactivityKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    List<CollectactivityKey> selectByExample(CollectactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") CollectactivityKey record, @Param("example") CollectactivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectactivity
     *
     * @mbg.generated Tue Dec 13 17:45:31 CST 2016
     */
    int updateByExample(@Param("record") CollectactivityKey record, @Param("example") CollectactivityExample example);
}